### ISSUE TITLE
@aws-amplify/ui-react/styles.css does not exist in location referenced by docs

### ISSUE THREAD

**Issue by k-wolf-dev** [aws-amplify/amplify-ui#1023]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

Created a new Amplify App and used the latest version of the Authenticator.   

NPM'd all of the appropriate packages.

Styles.css is not in the directory referenced in the Amplify Authenticator Documentation.

https://ui.docs.amplify.aws/getting-started/installation

`@aws-amplify/ui-react/styles.css`

After some poking around, found styles.css in

`@aws-amplify/ui-react/node-modules/@aws-amplify/ui/dist`

Looks like others have hit this issue as well:

https://stackoverflow.com/questions/70382924/unable-to-resolve-path-to-module-aws-amplify-ui-react-styles-css

Two questions:

1/. Is this the right styles.css we should be using?    

2/.  Is there a smaller / min version of styles.css that just covers the base authenticator styling/functionality (versus having other styling for sliders, etc..)

Opened a new bug since the other bugs related to this had other environments/issues reported.  This was a plain vanilla set-up.

Thanks!

### What's the expected behaviour?

Styles.css should be in the location referenced in the documentation.

### Help us reproduce the bug!

As per the above.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @k-wolf-dev, thanks for reporting this issue. What build system / bundler are you using? We just fixed a similar issue https://github.com/aws-amplify/amplify-ui/issues/1020 which occurred when using parcel.

**Comment by k-wolf-dev** [comment]
@reesscot  -- thanks!  

We use webpack

**Comment by reesscot** [comment]
Hi @k-wolf-dev, do you know which version of Webpack you are using?

**Comment by k-wolf-dev** [comment]
Sure.  

Webpack version is:  webpack@5.65.0 

Though curious why the initial npm package install wouldn't place the file in the referenced place?  (or the docs would note this)?

Thanks!

**Comment by reesscot** [comment]
Are you getting any error messages from the Webpack build? I tried importing the styles via Webpack 5.65.0 and had no issues.

In answer to your question, the styling in the current release lives in the ui package. The `import @aws-amplify/ui-react/styles.css` resolves to [@aws-amplify/ui-react/dist/index.css](https://unpkg.com/browse/@aws-amplify/ui-react@2.1.5/dist/index.css) which contains the following code:
```
@import"@aws-amplify/ui/styles.css";
```
Webpack should correctly resolve this to the `@aws-amplify/ui/styles.css` in node_modules. Note that `./styles.css` in ui package should in turn be resolved to `dist/styles.css` via the [exports](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/package.json#L11) property in ui's package.json. This is the file that you mentioned, which contains the necessary styling for Authenticator and all other UI primitives (in answer to your second question, no there isn't a separate styling file just for Authenticator).

The next release will move the styles from the ui package over to the ui-react package in order to fix import issues we've seen in the `Parcel` bundler. I've not been able to reproduce an import issue in Webpack, so if you are still experiencing an issue, I'd love to know more about your configuration.

**Comment by k-wolf-dev** [comment]
Thanks. 

I think there is a more fundamental issue going on for us.

-- We created a simple React App using create react app

-- We configured and set up amplify per the documentation (Npm all required amplify packages, etc..)

In our`@aws-amplify/ui` directory under `node_modules`, there is no styles.css.  All we see is the following:

LICENSE
dist
lib
package.json
postcss.config.js
src
tsconfig.json
webpack.config.js

I looked at the package.json under ui and didn't see an exports property there for /dist/styles.css 

The other post i referenced from Stack Overflow seem to have the same issue.

Thanks!

**Comment by reesscot** [comment]
Yes it's expected that you wouldn't find it in the root of the `@aws-amplify/ui` in `node_modules`. However, you should find it at dist folder (`node_modules/@aws-amplify/ui/dist/styles.css`). The reason this shouldn't be an problem is because Webpack should look at the [exports](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/package.json#L11) property in ui's package.json and resolve `styles.css` to `dist/styles.css`. 

I haven't been able to reproduce an CSS import issue with CRA. A few follow up questions that may help me reproduce this:
1. Did you eject your app from CRA? Usually CRA doesn't have a webpack.config.js otherwise.
2. What's the exact error message you're getting?

**Comment by reesscot** [comment]
Can you also provide the `aws-amplify` version you're using? There was an issue with that `aws-amplify` for versions below 4.3.11 and CRA last week.

**Comment by k-wolf-dev** [comment]
Sure:

@aws-amplify Version is:  6.14.10

1/  No; we didn't eject our App from CRA.  

2/. We didn't even get to the build step -- we were in development mode and styles.css was not in the place referenced by the Amplify UI sample code/docs / could not be resolved with VS.

However, styles.css is not in our `node_modules/@aws-amplify/ui/dist` folder either.

There is a style.css but not styles.css

The only place I was able to find styles.css was:

`@aws-amplify/ui-react/node-modules/@aws-amplify/ui/dist`

Not sure if 1/ explains this issue -- but since many users start with CRA, expected styles.css to be in the right place per the Amazon sample docs.

**Comment by reesscot** [comment]
Hi @k-wolf-dev,
I am still unable to reproduce this issue using CRA. Would it be possible to share a demo github repo demonstrating the issue you're seeing?

**Comment by dmost714** [comment]
I have a similar issue using vite.
Steps to reproduce:

1. `yarn create vite`, pick 'react' then 'react-ts'
2. cd into project directory
3. `yarn dev` - page renders, move along
4. `yarn add @aws-amplify/ui-react aws-amplify`
5. replace `App.txs` code with sample code from `App.js` Take it for a test drive section [https://ui.docs.amplify.aws/](url)
6. `yarn dev`, error below occurs.
7.  Follow vite instructions from [https://ui.docs.amplify.aws/getting-started/installation#vite](url)
8. error still occurs.

Error:
`[vite] Internal server error: Failed to find '@aws-amplify/ui/styles.css'`

**Comment by dmost714** [comment]
The issue reported above is fixed by applying [https://github.com/aws-amplify/amplify-ui/issues/1020#issuecomment-998361143](url) the upcoming patch.

**Comment by reesscot** [comment]
Closing as the [fix](https://github.com/aws-amplify/amplify-ui/issues/1020#issuecomment-998361143) has been released. Please reopen if you're still having the same issue with the latest version of @aws-amplify/ui-react
