### ISSUE TITLE
Default country code for the phone_number field is undefined for Authenticator

### ISSUE THREAD

**Issue by averyyip** [aws-amplify/amplify-ui#1043]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Gatsby

### Please describe your bug.

In the Authenticator UI, I specify that I would like to collect `phone_number` as a `signUpAttributes`. The UI defaults to the `+1` country code. However, upon creating a user with the defaulted country code, the country code sent is actually `undefined` which causes cognito IDP API to error due to invalid phone number.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/12945091/147184100-70a859d1-918e-4afb-a890-4c9ae24e7af9.png">

### What's the expected behaviour?

The default country code should be `+1` as opposed to `undefined`.

### Help us reproduce the bug!

UI repro: https://www.loom.com/share/4492a233b6394adda95e475b807247b1

When I select a country code from the dropdown prior to creating an account, the country code is no longer undefined. It appears to be an issue with the initial default state of the country code.

### Code Snippet

```typescript
<AmplifyProvider>
      <Authenticator
        loginMechanisms={['email']}
        socialProviders={['google']}
        signUpAttributes={['given_name', 'family_name', 'phone_number']}
      >
        {({ user }) => {
          setAuthUserState({
            // @ts-ignore
            email: user.attributes.email,
            // @ts-ignore
            firstName: user.attributes.given_name,
            // @ts-ignore
            lastName: user.attributes.family_name,
          });
          return children;
        }}
      </Authenticator>
    </AmplifyProvider>

```

### Additional information and screenshots

n/a

**Comment by ErikCH** [comment]
Hi @averyyip !

There was a similar issue with our phone number drop down that we fixed on our latest `@next` version of the authenticator.  It should be released the first week of January.

In the meantime, could you try installing the `@aws-amplify/ui-react@next` version of the library and see if that helps resolve the issue?

Related to: 
https://github.com/aws-amplify/amplify-ui/pull/1014

**Comment by akbog** [comment]
Hi @ErikCH,

Thanks for the suggestion!

Have been experiencing the same issue here, even with the @aws-amplify/ui-react@next version of the library.

**Comment by ErikCH** [comment]
Hi @akbog ! I'll look at this further. Must be a different issue.

**Comment by walkinjack** [comment]
On the @next version the default selected country_code isn't set in the formData on initial load; I had to add custom validation to set it:

```
if (!formData.country_code) {
    formData.country_code = "+1"
}
```
### Here is the full code I'm using as a work around:

```
<Authenticator
    // Default to Sign Up screen
    initialState="signUp"
    // Customize `Authenticator.SignUp.FormFields`
    components={{
        SignUp: {
            FormFields() {
                const { validationErrors } = useAuthenticator();

                return (
                    <>
                        {/* Re-use default `Authenticator.SignUp.FormFields` */}
                        <Authenticator.SignUp.FormFields />

                        {/* Append & require Terms & Conditions field to sign up  */}
                        <CheckboxField
                            errorMessage={validationErrors.acknowledgement}
                            hasError={!!validationErrors.acknowledgement}
                            name="acknowledgement"
                            value="yes"
                            label="I agree to receive periodic emails"
                        />
                    </>
                );
            },
        },
    }}
    services={{
        async validateCustomSignUp(formData) {
            //prevent null country code
            if (!formData.country_code) {
                formData.country_code = "+1"
            }
            if (!formData.acknowledgement) {
                return {
                    acknowledgement: 'You must agree to sign up',
                };
            }
        },
    }}
>
    {({ signOut, user }) => (
        <main>
            <h1>Hello {user.attributes.name}</h1>
            <button onClick={signOut}>Sign out</button>
        </main>
    )}
</Authenticator>
```

### What is happening
On load of the sign up form, +1 is the default country code, however, the country_code variable in formData isn't set to the default.

Expected behavior: on load  country_code = +1
Actual behavior: on load  country_code = Unknown Variable

You can prevent the error by changing the country code drop down from +1 to something else, and then back to +1 :D

**Comment by averyyip** [comment]
@walkinjack solutions works! Thanks!

**Comment by slaymance** [comment]
This issue has been patched as part of the release [@aws-amplify/ui@3.0.9](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui%403.0.9). The fix is present in the following framework releases:
- [@aws-amplify/ui-angular@2.0.9](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-angular%402.0.9)
- [@aws-amplify/ui-react@2.1.10](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react%402.1.10)
- [@aws-amplify/ui-vue@2.0.9](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-vue%402.0.9)

This issue uses the default country/region code in the case that `formValues` doesn't contain a `country_code` value (which is common if the selector isn't updated by an end-user). You can check out the changes in [PR 826](https://github.com/aws-amplify/amplify-ui/pull/826).

I'll mark this issue as closed pending response for the next few days in case anyone has further questions or concerns.

**Comment by akbog** [comment]
Can confirm as well that the solution works! Thank you very much.
