### ISSUE TITLE
Bug: Authenticator Create Account Button Element Styles

### ISSUE THREAD

**Issue by Jesmaster** [aws-amplify/amplify-ui#1133]
The Authenticator "Create Account" button gets the following element styles

`    border-radius: 0px;
    font-weight: normal;`

Very easy to replicate, simply place an Authenticator component, you will see the Sign In button has no hard styles on the element. Click the Create Account tab and look at the button and the font is no longer bold and the border radius is gone. There should be no styles added on the element level to the button as these are overriding the default theme button styles.

You can see this in the documentation page as well:
https://ui.docs.amplify.aws/components/authenticator#initialstate

**Comment by reesscot** [comment]
@Jesmaster thanks for reporting this issue! Are you interested in submitting a PR to fix this? This would be a great first issue to tackle if you'd like to contribute.

You can see the issue is on [SignUp.tsx#L66](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/SignUp/SignUp.tsx#L66) and [SignUp.tsx#L73](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/SignUp/SignUp.tsx#L73). Removing these lines should solve the issue.
