### ISSUE TITLE
Is it possible for AWS Amplify Access Control to support 1000s of users logging in at same time?

### ISSUE THREAD

**Issue by Consigliere-nft** [aws-amplify/amplify-ui#1231]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

create react app

### Please describe your bug.

Is there any problems with 1000s of users using the built in Amazon AWS Amplify access control user/password in order to access a site? Will it support that many concurrent logins?

### What's the expected behaviour?

everyone can login at same time and access site (even all using the same password)

### Help us reproduce the bug!

Have 2000 concurrent logins using the built in Amazon AWS Amplify access control user/password feature, does it crash or work?

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Hi @Consigliere-nft !

Let me try to understand your scenario. Cognito, which handles the authentication/authorization system that the Amplify library uses, can handle thousands of users logged in. It uses a JWT token system, so that should not be an issue. Users can be logged in at the same time as well. 

I don't recommend having everyone use the same login though. You could though. The system doesn't prevent you. Does that help answer your question?
