### ISSUE TITLE
Attributes of the user object in the authenticator

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-ui#1453]
### On which framework/platform would you like to see this feature implemented?

React, Angular, Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Integrating the [quickstart](https://ui.docs.amplify.aws/components/authenticator#quick-start) of the authenticator gives me the Cognito subId instead of the username or user email. There is no documentation on attributes available for the user object. (e.g. below is `<h1>Hello {user.username}</h1>`)

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/2429410/156474441-1d86fea6-e0cc-4a26-91c3-8eaa9c5e26a0.png">

### Please describe a solution you'd like.

i'd like to be able to show my user's email or username

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hello @swaminator !

We've made some updates to the attributes and it should be showing correctly.

If you create an app with `Username` as the default auth sign in method, as seen in the [Getting Started Guide](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/), then it will show the correct user name. 

However, if you choose `email` as the default sign in method, and you try to display `user.username`, then it will show the id, since there is no `username` associated with the account.

I'm going to close this, please re-open it, if it happens again.
