### ISSUE TITLE
[Feedback] Amplify Authentication documentation is outdated.

### ISSUE THREAD

**Issue by breencp** [aws-amplify/amplify-ui#1565]
**Page**: [`/ui/auth/authenticator/q/framework/[framework]`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular/#breaking-changes-for-withauthenticator)

**Feedback**:

This documentation appears to be old.  `AmplifyUIAngularModule` has been replaced with `AmplifyAuthenticatorModule`, correct?  There is a link to https://ui.docs.amplify.aws/components/authenticator?platform=angular but the content there is incomplete.  How do I do the equivalent of `<div *ngIf="authState === 'signedin' && user" class="App">` with the new framework?

**Comment by ErikCH** [comment]
Hi @breencp and @RichWK !

Sorry for the delay, we have updated that link and it now points to our new [documentation site](https://ui.docs.amplify.aws/).

Since our release last year, we've been adding more customization features, including a headless mode, for [Angular](https://ui.docs.amplify.aws/components/authenticator?platform=angular#headless-usage), [Vue](https://ui.docs.amplify.aws/components/authenticator?platform=vue#headless-usage), and [React](https://ui.docs.amplify.aws/components/authenticator?platform=react#headless-usage).

For all the frameworks we added in a [`authStatus`](https://ui.docs.amplify.aws/components/authenticator?platform=react#access-auth-state) feature that will return back if the user is `authenticated`, `configuring` or `unauthenticated`. 

For example, you can use `authStatus` to decide which page to render.

```
import { useAuthenticator } from '@aws-amplify/ui-react';

const App = () => {
  const { authStatus } = useAuthenticator(context => [context.authStatus]);

  // Use the value of authStatus to decide which page to render
 return (
    <>
      {authStatus === 'configuring' && 'Loading...'}
      {authStatus !== 'authenticated' ? <Authenticator /> : <Home />}
    </>
  );
};
```

Does this cover the scenario you are looking for?

**Comment by breencp** [comment]
@ErikCH,

I reviewed the new documentation and it appears to be exactly what I was looking for.  I look forward to giving it a spin.  Thanks!

**Comment by ErikCH** [comment]
Thanks @breencp !
