### ISSUE TITLE
Authenticator Support Email and Phone

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#1913]
### On which framework/platform would you like to see this feature implemented?

React, Angular, Vue, Other

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

We'd like to be able to login via email and phone. Right now the Authenticator only supports login by email or phone. You can't do both at the same time.

https://app.asana.com/0/1201410500481323/1201377903144607

### Please describe a solution you'd like.

Provide a way to toggle between either. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
This was previously descoped, because there are a lot of DX with Sign in with Email or Phone Number option.

Notably, customer can only sign in with whichever they signed up -- so if they signed up with email, they must sign in with email and cannot sign in with phone number even if their phone is verified. Put short, this doesn't allow customers to sign in with both email and phone number, which is the desirable experience.

We looked at having some toggle button, but that still leads to DX issues because they have to remember which one they signed up with.

**Comment by reesscot** [comment]
Closing this out as we are not planning to implement this feature due to reasons mentioned above.
