### ISSUE TITLE
Can amplify-authenticator render hosted UI for federated logins?

### ISSUE THREAD

**Issue by foragerr** [aws-amplify/amplify-ui#232]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
```
$ amplify --version
4.17.2
```

I have a cognito user pool with only google as an Identity provider. When I addd `<amplify-authenticator></amplify-authenticator>` to my angular component, it renders a username/password form.

Can amplify-authenticator show a "Login with google" button? or maybe render the hosted-UI? Or should I be looking to implement that myself?

**Comment by ericclemmons** [comment]
A couple improvements resolve this issue for our `@next` release:

1. Social providers use Cognito User Pools by default (via `Auth.federatedSignIn`), since this is the default social configuration from Admin UI & the CLI.

    > ![Screen Shot 2021-11-05 at 11 40 34 AM](https://user-images.githubusercontent.com/15182/140546769-8bbfd60c-3256-4723-8093-644fa4b29ea3.png)
    > – https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#loginmechanisms

1. Zero-config support from #626 will make **`<Authenticator>` automatically show the correct login mechanisms (including Google, in your case) without any additional configuration**.
