### ISSUE TITLE
Authentication error messages are not accessible to assistive devices

### ISSUE THREAD

**Issue by sawyerh** [aws-amplify/amplify-ui#233]
**Describe the bug**
The "toast" component used for displaying authentication error messages, such as "Username cannot be empty", lacks sufficient markup to achieve an accessible experience for assistive device users, such as screen readers. Additionally, there is no built-in way to create a custom error message component to create a more accessible experience. For projects that are required to be [Section 508 or ADA compliant](https://www.section508.gov/blog/do-section-508-accessibility-standards-apply-to-mywebsite), which is most websites, [this is a big deal](https://www.applause.com/blog/what-dominos-case-means-for-accessibility) and prevents developers from using the Amplify UI components. 

**To Reproduce**
[Some tips for doing an accessibility review are available here](https://developers.google.com/web/fundamentals/accessibility/how-to-review). (I assume/hope AWS has accessibility experts to help reproduce and address this further).

**Expected behavior**

The exact solution varies, but in general:

- Move the focus to the first form control that has the error or move the focus to the common error message. Ensure a screen reader is alerted to this new content.
- Add inline error messages to form fields
- Associate the inline errors with form fields by using the `aria-describedby` attribute

WCAG 2.0 specifies the following guidelines for accessible form validation and error identification:

- [SC 3.3.1 Error identification](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-identified.html)
- [SC 3.3.3 Error suggestions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-suggestions.html)

**Comment by ErikCH** [comment]
Hi @ashika01 and @sawyerh 

With our new authenticator we have taken accessibility in mind with all our designs. Recently I pushed up a PR to add in a `role=alert` to all the alert messages and errors. This will give screen readers a better indiction of when errors occur. We are also using `aria-invalid` in several of our inputs as well.

We decided not to change focus on alert's because we feel like it's an unexpected experience for the user. However, we are always up for suggestions on how to make this better.

I believe this is a good first start, and we'd really like more feedback on more places we can make our app more accessible. 

You can check out our new authenticator documents here to get started.
https://ui.docs.amplify.aws/ui/getting-started/installation

**Comment by ErikCH** [comment]
I'll close this now. Please reopen it if needed.
