### ISSUE TITLE
how can i save user to userpool  suing sign up with facebook and amazon

### ISSUE THREAD

**Issue by deepdil-sp** [aws-amplify/amplify-ui#2473]

**Comment by slaymance** [comment]
Hey @deepdil-sp, we'll need some more information from you in order to help you. Are you using the Amplify UI Authenticator? Which framework and version are you using? Have you tried signing up a user through the Amplify Console? Have you tried signing up a user through your application using the Authenticator component?

**Comment by Milan-Shah** [comment]
@deepdil-sp We havent heard back from you. We are closing the issue but feel free to open a feature-request or an issue on our repository if you are having a problem or has a suggestion for a feature that may be useful for all our customers.
