### ISSUE TITLE
Components should not scale to html font-size property

### ISSUE THREAD

**Issue by pak11273** [aws-amplify/amplify-ui#2567]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

If I set my global font-size Amplify components scale with the value:
```js
// index.scss
html {
    font-size: 62.5%;
}
body {
    font-size: 1.6rem;
}
```
This is a common best practice for setting font-sizes.  Authenticator app shrinks along with the %. 
 What if I wanted to go smaller in size like 6.25%? - which is not  uncommon - the Authenticator component becomes barely visible.  All my components remain fine.  The structure of Amplify components should not be coupled with **html.font-size**.

I have looked into all of the classes but I haven't come across anything that will override this.  

### What's the expected behaviour?

Expected behaviour should behave like all my other components.

### Help us reproduce the bug!

1. Create a react or nextjs app.
2. Add a global css or scss file and change the font-size to be a % of the default browser font-size

### Code Snippet

```typescript
// Put your code below this line.
html {
    font-size: 62.5%;
}
body {
    font-size: 1.6rem;
}
```

**Comment by 0618** [comment]
Thanks for reporting this issue. We'll look into it.

**Comment by reesscot** [comment]
Hi @pak11273,

Thanks for reporting this issue. Amplify UI styling assumes the default font-size of `16px` for the `rem` unit. This allows developers to scale the UI at different breakpoints by adjusting the root font-size like this:

```css
/**
  * Scales down UI components by 20% on mobile-sized screens
  */
@media (max-width: 48rem) {
  :root {
    font-size: 80%;
  }
}
```
From an accessibility perspective, using the `rem` units for all our sizing and spaces allows application users to scale up the application from their browser default font size settings.

If I understand your use case correctly, it sounds like you are scaling down the default font size in order to make `1 rem === 10px`. This would make `rem` units easier to work with, is that correct? As the CSS is currently written, I don't think we can support that scenario. 

We could consider making a breaking change and moving over to `px`, but then Amplify UI components would lose the accessibility benefits of using `rem`. If you are using `rem` in your application for the same reasons, then our components would no longer scale at all.

The best solution if you want to continue resetting `rem` values to `10px` instead of using default `16px` would be to reset all the default theme values that use `rem` to the appropriate new values:

Here's an example of resetting the `xxs` space:
```jsx
export const myTheme = {
  name: 'my-theme',
  tokens: {
    space: {
      xxs: { value: ''0.4rem" }, // 0.25rem * 16px/rem = 4px, which is 0.4rem
    },
  },
};
```
You'd need to do the same for all the design tokens using rem:

See:
https://ui.docs.amplify.aws/react/theming/default-theme/sizes
https://ui.docs.amplify.aws/react/theming/default-theme/typography

Then use your `theme` as described here:
https://ui.docs.amplify.aws/react/theming#getting-started

**Comment by pak11273** [comment]
@reesscot Thanks for the detailed and speedy response.  This really gives me more confidence in this library.  I see what you are talking about and I am indeed trying to do the 10px to make calculations easier, but I'm fine with switching back to 16px in my current project ( i've built most apps like this anyhow ).   Thanks again and keep up the good work!
