### ISSUE TITLE
SMS is not send

### ISSUE THREAD

**Issue by alexlevy0** [aws-amplify/amplify-ui#3089]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo

### Please describe your bug.

I do not receive the validation sms

### What's the expected behaviour?

Receive the validation sms to confirm the phone number

### Help us reproduce the bug!

```
<Authenticator.Provider>
      <Authenticator
        signUpAttributes={[
          "phone_number",
        ]}
        loginMechanisms={[
          "phone_number",
        ]}

      >
        <View style={{ padding: 200 }}>
          <SignOutButton />
        </View>
      </Authenticator>
    </Authenticator.Provider>
```

### Additional information and screenshots

<img width="857" alt="Screenshot 2022-11-25 at 04 31 08" src="https://user-images.githubusercontent.com/6535861/203896409-a875a888-c003-48e3-ab4f-fcbda1940d10.png">
<img width="1299" alt="Screenshot 2022-11-25 at 04 37 30" src="https://user-images.githubusercontent.com/6535861/203896565-6b7b07ef-167d-4d1a-9efb-10fd115dd725.png">

**Comment by joebuono** [comment]
Hi @alexlevy0. We were not able to reproduce this issue, so we think that it may have something to do with how you've set up SMS. 

Can you confirm that these lines are included in your `aws-exports.js` file?
```
  aws_cognito_username_attributes: ["PHONE_NUMBER"],
  aws_cognito_signup_attributes: ["PHONE_NUMBER"],
  aws_cognito_mfa_types: ["SMS"],
  ```

In order to validate that your setup works, you can [send a test message](https://docs.aws.amazon.com/pinpoint/latest/userguide/messages-sms.html) from the AWS console. 

Here is a [blog post](https://aws.amazon.com/blogs/mobile/changes-coming-to-aws-amplifys-sms-based-authentication-workflows/) about configuring SMS-based authentication workflows. Let us know if that helps!

**Comment by alexlevy0** [comment]
Thank you, it works fine now
