### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by jbowen28** [aws-amplify/amplify-ui#3208]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

CRA

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

After modifying my code to use Authenticator.Provider and useAuthenticator, cannot compile the code that used to compile without error.  The typescript compiler outputs the following:

       ../../node_modules/@aws-amplify/ui-react/dist/types/components/Geo/LocationSearch/index.d.ts(1,37): error TS2307: Cannot find module 'maplibre-gl-geocoder' or its corresponding type declarations.
       ../../node_modules/@aws-amplify/ui-react/dist/types/primitives/types/responsive.d.ts(2,56): error TS2339: Property 'values' does not exist on type 'PartialObjectDeep<Breakpoints> | undefined'.
       ../../node_modules/@aws-amplify/ui-react/dist/types/primitives/types/responsive.d.ts(3,61): error TS2339: Property 'values' does not exist on type 'PartialObjectDeep<Breakpoints> | undefined'.

### What's the expected behaviour?

No typescript compiler errors.

### Help us reproduce the bug!

Use typescript compiler and the AWS Authenticator.Provider and useAuthenticator functions.

### Code Snippet

```typescript
// Put your code below this line.

```
	"dependencies": {
		"@aws-amplify/ui-react": "^4.3.0",
                "@maplibre/maplibre-gl-geocoder": "^1.5.0",
		"@material-ui/core": "^4.9.7",
		"@material-ui/icons": "^4.9.1",
		"@skyrepublic-toolkit/atlas-ui": "0.2.1-27u",
		"aws-amplify": "^5.0.7",
		"maplibre-gl": "2.1.9",
                 "maplibre-gl-js-amplify": "^3.0.0",
		"prop-types": "^15.7.2",
		"react": "^16.14.0",
		"react-dom": "^16.14.0",
		"react-native": "^0.71.0-rc.5",
		"react-router-dom": "^5.1.2",
		"react-scripts": "^5.0.1"
	},
	"devDependencies": {
		"typescript": "4.4.4"
	},

### Additional information and screenshots

I am just trying to use the basic headless AWS Authentication using Authenticator and Auth components.  The other AWS and maplibre-gl components are added to satisfy Authenticator and Auth components.

**Comment by reesscot** [comment]
@jbowen28 I'm working on reproducing this, if you have a minimal example repo, that would be very helpful. Can you share your `tsconfig.json` file? One possible workaround to try would be to turn on `skipLibCheck` in your `tsconfig` file:
```
{
  "compilerOptions": {
    "skipLibCheck": true,
```

**Comment by reesscot** [comment]
@jbowen28 I'm sorry you're having this issue, but I'm unable to reproduce these build errors using the dependencies listed above. 

![image](https://user-images.githubusercontent.com/6165315/209024855-9ec2a967-a9e1-4d3a-a3f7-4e3d59cb42ac.png)

![image](https://user-images.githubusercontent.com/6165315/209025386-dd9b0985-3d25-497e-bfe9-6c63ecd27b83.png)


I also have a few clarifying questions about a few of these dependencies that may help me reproduce this:
1. Is there a reason you have `react-native` in this project, it looks like you are using the web version of the Amplify UI React package.
2. Is `@skyrepublic-toolkit/atlas-ui` an internal package because I'm unable to install it from npm.
3. Can you try removing all the `maplibre-*` dependencies? Those are hard dependencies of `@aws-amplify/ui-react` so you shouldn't need to install them specifically.

**Comment by jbowen28** [comment]
@reesscot Thanks for looking into this issue.  After following your suggestions, I am no longer seeing the issue.  Also, thanks for the workaround for issue 3210 which I also ran into.  I am able to compile successfully now.  You can close this issue.
