### ISSUE TITLE
Custom style the  "WithAuthenticator" component

### ISSUE THREAD

**Issue by ChessMathNerd** [aws-amplify/amplify-ui#3440]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

This is my current App.js. I have basically been following the tutorial on getting authentication set up with AWS. I would like to be able to customize the styling of the Authentication component, and remove the requirement for an email to be entered when someone wants to sign up. Thanks!

[for amplify.txt](https://github.com/aws-amplify/amplify-ui/files/10771950/for.amplify.txt)

Right now, all the buttons at the sign in form are blue, and under the create account tab of the component, there is a required email field. I couldn't attach a screenshot, it wouldn't let me, but you can go to https://dev.d1lj0y1o63aw13.amplifyapp.com/ to see it. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
Hi @ChessMathNerd! 

Documentation for updating the default style of the `Authenticator` can be found [here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#css-style). 

Email or Phone Number is required for sign up in order to send a sign up confirmation with Amazon Cognito, more information can be found in the [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html).

Please let us know if that helps!

**Comment by ChessMathNerd** [comment]
Thank you. One more question. 
I am trying to use dynamoDB in my application (want to display database info on the client side browser page), which is hosted on amplify. the documentation I have found is very confusing and I cannot make sense of it. Do you guys have a youtube channel that gives tutorials on this kind of thing?

**Comment by calebpollman** [comment]
@ChessMathNerd Can you please open an issue with in the [Amplify JS github repo](https://github.com/aws-amplify/amplify-js) regarding your questions?

Going to close this ticket since the initial question has been addressed but please reopen if you continue having issues
