### ISSUE TITLE
Authenticator TextField placeholders are not translated

### ISSUE THREAD

**Issue by philipheinser** [aws-amplify/amplify-ui#3510]
All Authenticator text placeholders are missing from translation files. Example: `Enter your Confirmation Code`  https://github.com/aws-amplify/amplify-ui/blob/270d7553652592d0d419ee708043b8292c63336c/packages/ui/src/helpers/authenticator/constants.ts#L18 https://github.com/aws-amplify/amplify-ui/blob/270d7553652592d0d419ee708043b8292c63336c/packages/ui/src/i18n/dictionaries/authenticator/en.ts#L3

Originally posted by @philipheinser in https://github.com/aws-amplify/amplify-ui/issues/3444#issuecomment-1457088341

**Comment by wlee221** [comment]
Hi @philipheinser, thanks for reporting this issue! We'll need to do two things:

1. Add missing texts to `DefaultTexts` so that those texts are discoverable
2. Add missing translations for each language

We mostly rely on open source contributors for translations, so (2) will be treated as a feature request. We will work on (1) separately.

**Comment by reesscot** [comment]
@philipheinser You are correct, we are missing the `Enter your Confirmation Code` text from our dictionary. Are you interested in contributing a fix including the translation? Let us know, or we can get at least get the entry added to the `en` dictionary.
