### ISSUE TITLE
Overriding function calls in Authenticator doesn't work in Typescript

### ISSUE THREAD

**Issue by cjsilva-umich** [aws-amplify/amplify-ui#3915]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

When following along with the example [here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls) for overriding function calls of the Authenticator, typescript complains of a mismatch.

### What's the expected behaviour?

Overriding the function calls like in the documentation is successful. Would also love to have type definitions for the functions and the services.

### Help us reproduce the bug!

Using typescript, try to override the services as shown in the documentation.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by cjsilva-umich** [comment]
Also, trying to follow the suggested customization [practice shown here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#sign-up-fields) for anything other than SignUp results in errors about the FormFields. Omitting the FormFields results in errors that Components and FormFields are omitted. How can we customize the Authenticator components or behavior?
![Screenshot 2023-05-18 at 8 49 07 AM](https://github.com/aws-amplify/amplify-ui/assets/53909945/66c81460-b210-4a9b-8f5b-ce72d39b2cbd)
![Screenshot 2023-05-18 at 8 49 56 AM](https://github.com/aws-amplify/amplify-ui/assets/53909945/9ea268c1-101a-47a3-9165-c8c6ba654183)

**Comment by hbuchel** [comment]
Hi @cjsilva-umich, for the first link you supplied for [Overriding function calls](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls) I'm not able to reproduce a Typescript mismatch error from the code as-is supplied in the docs. If you're looking for the type definition for services, though, `AuthenticatorProps["services"]` should supply that. (screenshot below and [codesandbox example here](https://codesandbox.io/s/auth-override-functions-ngr1qx?file=/src/App.tsx:219-272)) Does that help?

<img width="855" alt="Example code in Visual Studio Code editor that shows type definitions when hovering over AuthenticatorProps[services] type" src="https://github.com/aws-amplify/amplify-ui/assets/376920/b2dc55ca-9cf1-416e-9262-ca6575298fcb">

Regarding customization of form fields for each route, yes, currently only SignUp supports `FormFields()` customization. For the others, like ConfirmSignup, it supports the [Components interface](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/hooks/useCustomComponents/defaultComponents.tsx#L11) EXCEPT for FormFields; so that means it supports Footer and Header customization. It is on our radar to improve the composability of Authenticator form fields, however we don't have anything to publicly follow for that work at the moment.  Please feel free to add any details to an existing feature request if you like; this one seems related to what you're trying to accomplish: https://github.com/aws-amplify/amplify-ui/issues/2152
