### ISSUE TITLE
Flashing colors don't appear on Liveness Component if bootstrap css is imported

### ISSUE THREAD

**Issue by leonardoliguori** [aws-amplify/amplify-ui#4413]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

eu-west-1

### Please describe your bug.

During the liveness check verification flashing bright colors should be appearing on top of the video.
They do not appear if bootstrap css is imported.

### What's the expected behaviour?

Flashing colors during the liveness check verification.

### Help us reproduce the bug!

Create a new create-react-app project with react-bootstrap@2.8.0, bootstrap@5.3.1, aws-amplify@5.3.10, @aws-amplify/ui-react-liveness@2.0.6 and @aws-amplify/ui-react@5.3.0

### Code Snippet

```javascript
import './App.css';
import 'bootstrap/dist/css/bootstrap.css';
import {ThemeProvider} from '@aws-amplify/ui-react';
import {Amplify} from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import awsexports from './aws-exports';
import {FaceLivenessDetector} from '@aws-amplify/ui-react-liveness';

Amplify.configure(awsexports);

function App() {
  const handleAnalysisComplete = () => {...};

  return (
        <ThemeProvider>
          <FaceLivenessDetector
              sessionId={'mySessionId'}
              region="eu-west-1"
              onAnalysisComplete={handleAnalysisComplete}
              onError={(error) => {
                console.error(error);
              }}
          />
        </ThemeProvider>
  );
}

```

**Comment by hbuchel** [comment]
Hi @leonardoliguori I tested out an app that loads in the latest Bootstrap css and could reproduce your issue. Unfortunately Bootstrap css includes some conflicting styles that use an `!important` rule:
```
[hidden] {
  display: none !important;
}
```
The `hidden` attribute on a canvas element, which our flashing colors use, isn't quite the same as setting it to `display: none`, though, and this makes it a little tricky to override. I don't know why they include this in their stylesheet :(

If you load in a custom stylesheet (after bootstrap and after our styles.css), you can try this (kind of ugly) CSS:
```
.amplify-liveness-freshness-canvas[hidden] {
  display: block !important;
}
.amplify-liveness-freshness-canvas[style*='display: none'] {
  display: none !important;
}
```
You'll want to test this across devices/browsers though.

**Comment by leonardoliguori** [comment]
Thank you @hbuchel, the custom CSS solution you provided works. 
I hope a more elegant solution could be found in the future to integrate both css.

**Comment by hbuchel** [comment]
Glad that it worked for you. I'm going to mark this as closed without a plan to fix. We do try to be good "neighbors" with other design systems/tooling but the issue here is really with Bootstrap css overreaching with its `hidden` attribute !important styling. Please feel free to open a new issue if there is anything else we can help with.

**Comment by ignatremizov** [comment]
Hi! I confirmed the same root cause with Tailwind 4 preflight too, not just Bootstrap.

Tailwind preflight includes:

```css
[hidden]:where(:not([hidden="until-found"])) {
  display: none !important;
}
```

In my case, `.amplify-liveness-freshness-canvas` is created and later receives inline `display: block`, but the `hidden` attribute remains present. Because of the global `[hidden]` rule, computed `display` stays `none` and the `FaceMovementAndLightChallenge` color sweeps never become visible.

Removing the hidden attribute at runtime also immediately brings the color sweeps back.

The CSS workaround from this thread works for Tailwind, but in my case it also needed to live in a Tailwind layer to beat preflight correctly:

```css
@layer theme {
  .amplify-liveness-freshness-canvas[hidden] {
    display: block !important;
  }

  .amplify-liveness-freshness-canvas[style*='display: none'] {
    display: none !important;
  }
}
```

So this issue is reproducible with Tailwind 4 preflight as well, and the layer placement mattered for the workaround, just FYI.
