### ISSUE TITLE
useAuthenticator does not refresh tokens or update user object

### ISSUE THREAD

**Issue by pfgallagher** [aws-amplify/amplify-ui#4511]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

When using `useAuthenticator`, the `user` object does not appear to automatically refresh when the tokens expire / trigger a re-render. 

### What's the expected behaviour?

The tokens should automatically refresh when they expire and trigger a change to `user`.

### Help us reproduce the bug!

Initialize an app using create-react-app, add the snippets below, set the token expiration to the minimum (5 minutes), and wait for the tokens to expire.

### Code Snippet

```typescript
// index.tsx
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

Amplify.configure({
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: '<poolId>',
  aws_user_pools_web_client_id: '<clientId>',
  authenticationFlowType: 'USER_PASSWORD_AUTH',
});

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <Authenticator loginMechanisms={['email']} signUpAttributes={['given_name', 'family_name']} passwordSettings={{
    passwordPolicyMinLength: 12,
    passwordPolicyCharacters: [],
  }}  >
    <App />
  </Authenticator>
);

// App.tsx
import { useEffect } from 'react';
import './App.css';
import { useAuthenticator } from '@aws-amplify/ui-react';

function App() {
  const { user } = useAuthenticator();
  useEffect(() => {
    console.log("user updated:", user);
  }, [user])
  return (
    <div className="App">
    </div>
  );
}

export default App;

```

**Comment by hbuchel** [comment]
Hi @pfgallagher we don't have much control over the token expiry, but before I send this over to the JS team, are you using `Authenticator.Provider`? This needs to wrap your application in order to use useAuthenticator. There are some more details on that here. https://ui.docs.amplify.aws/react/connected-components/authenticator/advanced#useauthenticator-hook If not, can you try that and see if it resolves your issue?

**Comment by hbuchel** [comment]
Talked to a team mate and it sounds like the user object from useAuthenticator is not always 1:1 with that from Auth; and we can not intercept every hub event because it could impact performance so this likely is something we cannot fix on the UI side. 

Instead, you could try getting the user object directly from `Auth.currentAuthenticatedUser` More details on that here: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#retrieve-current-authenticated-user

**Comment by pfgallagher** [comment]
Thanks, @hbuchel ! Based on these [docs](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#managing-security-tokens), I understood this to be a feature of the library. Token refresh seems like a pretty common use case. 
`user` does seem to get updated if you call `Auth.currentAuthenticatedUser` /`Auth.currentSession` before any requests or call them on an interval, but doesn't seem ideal, particularly when dealing with e.g. idle users and users waiting for batch jobs. I tried listening for `Hub` `tokenRefresh` events to no avail, as well.

**Comment by reesscot** [comment]
Hi @pfgallagher,
We do listen to the Hub `tokenRefresh` event in the Authenticator. I [tested out the token refresh logic](https://github.com/reesscot/cra-starter/blob/start/src/App.js#L17) and it appears to be working as expected. Token refresh happens on demand when you call an Amplify API which needs Auth, that's why you see the `user` being updated when you call `Auth.currentAuthenticatedUser` or `Auth.currentSession`. There is no logic to refresh tokens unless you are trying to access something that requires Auth (it would be a lot of unnecessary API calls). So long as the access token is still valid, if your customers try to access an API, their token will be automatically refreshed, and the `user` object will be updated. If your customers do nothing, no token refresh API call will be made.

What is your use case, i.e. what are you trying to accomplish? It sounds like you might be trying to force customers to exit the application after a given amount of time? In that case your best option might be to set a timer on their total time based on your configured Refresh token expiration and force sign out. Authenticator listens to the signout Hub event and will show the signin screen.
