### ISSUE TITLE
custom style issues with latest ui-react version; attributes missing; examples broken

### ISSUE THREAD

**Issue by renschler** [aws-amplify/amplify-ui#4977]
I have one app running `"@aws-amplify/ui-react": "^4.3.3"` and one app running `"@aws-amplify/ui-react": "^6.1.2"`

I have custom css that references various attributes that are supposed to be present on the authenticator, but they seem to be missing in the latest versions.

Not sure if this is a bug or if the documentation just needs to be updated.

https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#additional-css-styling
![Screenshot 2024-02-05 at 11 33 54 AM](https://github.com/aws-amplify/amplify-ui/assets/3973468/2f29b79b-3d20-42e3-9ece-f7b2cba8e180)

This no longer works with the most recent version of ui-react because the data-variation attribute isn't on the sign-in button.

I also have a data-state attribute reference that no longer works.

I also tried the example code from the documentation and my authenticator didn't change at all visually after implementing those changes.
https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#css-style

![Screenshot 2024-02-05 at 11 36 27 AM](https://github.com/aws-amplify/amplify-ui/assets/3973468/224c959a-77c0-40da-87fc-78315b51a1fa)

**Comment by hbuchel** [comment]
Hi @renschler Sorry about that, looks like we have some documentation to update in those two places. I can open a PR shortly.

For the first example, we removed data attributes from our components that were previously used for styling as part of the v6 release. Instead of `.amplify-button[data-variation='primary'] ` you can use `.amplify-button--primary`

For the second example, depending on what you want to change, you can target the component css variables directly. So something like this works:

```css
[data-amplify-authenticator] {
 --amplify-components-tabs-panel-background-color: pink;
  --amplify-components-field-label-color: red;
  --amplify-components-button-primary-background-color: red;
}

```

I'll keep this open while we update the documentation.

**Comment by renschler** [comment]
Thanks! Yes I also realized later that the older app is on v5 amplify and the newer one is on v6 amplify, so it's not just the ui-react versions that differ.

**Comment by hbuchel** [comment]
@renschler We will have updated documentation in our next release for styling the Authenticator with this PR https://github.com/aws-amplify/amplify-ui/pull/4981. Thanks for bringing this to our attention!
