### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by adityatamhane** [aws-amplify/amplify-ui#5313]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Create React App for frontend and backend API in Go

### What browsers are you seeing the problem on?

Chrome, Safari

### Which region are you seeing the problem in?

ap-south-1

### Please describe your bug.

After getting the session ID when we started for FaceLivenessDetector we got an error saying that the WebSocket connection to "$MyWebSocketPath" failed and after 5 Sec got a CONNECTION_TIMEOUT error

![Screenshot 2024-06-13 at 4 55 53 PM (2)](https://github.com/aws-amplify/amplify-ui/assets/38723475/05fe42a9-a804-4ccc-aea2-72937b201d7e)

### What's the expected behaviour?

It should start FaceLivenessDetector video.

Also, we want to check or debug more about why the WebSocket is failing in documentation not got more information about same 

### Help us reproduce the bug!

Done the setup as per the documentation but was unable to debug more on why web socket is failing

### Code Snippet

N/A

### Console log output

![Screenshot 2024-06-13 at 4 55 53 PM (2)](https://github.com/aws-amplify/amplify-ui/assets/38723475/c9ee58f0-249e-49ef-bcde-c0c355349a61)

### Additional information and screenshots

want to know about the possibility of failing WebSocket connection

**Comment by esauerbo** [comment]
Hi @adityatamhane thanks for creating this issue. Are you seeing this error consistently or only sometimes? The connection timeout error is typically due to slow network speeds. (I was able to reproduce this by artificially throttling my network.) We time out after 5 seconds of attempting to create the websocket connection. https://github.com/aws-amplify/amplify-ui/blob/7450f80cd993d01dd803f2bc807ca062f247a568/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/CustomWebSocketFetchHandler.ts#L168
Can you try running this on a faster network and see if that resolves the issue? 

And regarding the documentation, I think it makes sense to add a note about this; we'll discuss as a team and consider adding an additional item about the connection timeout.

**Comment by adityatamhane** [comment]
Hi @esauerbo yes I am seeing this error consistently. Also, I have pretty good internet speed.
Ones we start video check first it instantly shows WebSocket connection failed and after 5 second it shows CONNECTION_TIMEOUT

**Comment by esauerbo** [comment]
@adityatamhane from the error message you provided above, the region says `ap-soth-1` which seems like a typo. Try updating that and see if that works.

**Comment by adityatamhane** [comment]
@esauerbo So sorry My bad yes it was a typo error in the region name. Now it's working Fine. 
Thanks for your valuable time @esauerbo. closing this issue now
