### ISSUE TITLE
(@next) Authenticator sends field data to Cognito even if field was emptied

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/amplify-ui#590]
### To reproduce

1. run `amplify-pull` on `environments/auth-with-email-and-custom-attributes`
2. `yarn react dev && yarn next-example dev`
3. Navigate to `http://localhost:3000/ui/components/authenticator/custom-sign-up-fields`
4. Type any string to "Preferred Username" and then delete it to make it empty
5. Fill out the rest of the form and submit

You'll see that sign up request goes through, even though it should error because `Preferred Username` is empty. Inspecting the network tab shows that authenticator sent a response with empty string, which is valid to Cognito's pov.

![image](https://user-images.githubusercontent.com/43682783/139297130-c212d3a8-75e3-4af2-bb92-164904e37484.png)

### Solution
[`handleInput`](https://github.com/aws-amplify/amplify-ui/blob/3143deff199a9aab367f253020205d3e2f25fc5b/packages/ui/src/machines/authenticator/actions.ts#L97-L106) should delete the current input field key/value off from context if the new value is empty, instead of setting it to an empty string.

**Comment by ericclemmons** [comment]
Good point.  I'm trying to think of when `''` is valid & should be allowed vs. always pruning `''` out of the `formValues`.

That's what's annoying about forms – ambiguity =/

An alternative to _this implementation_ is that **we should be setting this as a required field**, since it's custom (so the responsibility is on the custom implementation, not our state machine?)

https://github.com/aws-amplify/amplify-ui/blob/6f49be811dab05b43fa611d084803be279fafa11/examples/next/pages/ui/components/authenticator/custom-sign-up-fields/index.page.tsx#L36-L41

This could be:

```diff
<TextField 
   label="Preferred Username" 
   labelHidden={true} 
   name="preferred_username" 
   placeholder="Preferred Username" 
+  isRequired
 /> 
```

**Comment by ericclemmons** [comment]
@wlee221 When we do https://github.com/aws-amplify/amplify-ui/issues/623, this will actually _remove_ `preferred_username` from requiring manual setup and we can add `required` by default to the field.

That way our `handleInput` doesn't have to become opinionated and potentially get it wrong. (since empty strings are valid values)

**Comment by wlee221** [comment]
Sounds good, I'll create a PR that enforces `isRequired` on those fields.
