### ISSUE TITLE
Examples on new <Authenticator/> instead of the HOC withAuthenticator, migration docs.

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#640]
As much as I like the new design and its extensive configuration, I will prefer the latest stable release approach with `AuthState` and `onAuthUIStateChange` as seen in this docs: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#recommended-usage. 

Using the past  `<AmplifyAuthenticator/>` is more component composition friendly compared to the new HOC `withAuthenticator`. I  guess the new UI is not backward compatible as I have tried to simply replace `<AmplifyAuthenticator/>` with the new `<Authenticator/>`, but it doesn't work. Will you support the Authstate approach or withAuthenticator is the only future?

**Comment by ericclemmons** [comment]
@artidata I totally agree. We'll roll this in with #576 & #254.

So the **primary** usage will look like:

https://github.com/aws-amplify/amplify-ui/blob/f84e9949bd98b20fe8d1dff85e30ae69f2356351/examples/next/pages/ui/components/authenticator/sign-up-with-attributes/index.page.tsx#L3-L15

This is different than the previous `<AmplifyAuthenticator>` **that would still render `children` even if not logged in**.

As for `onAuthUIStateChange`, there are 2 different alternatives:

1. `useAuthenticator` which returns `user`, `signOut`, and several other methods to hook into `Authenticator` (#254).
2. A `useAuth` React hook (#601), which is a live hook around Amplify `Auth`.

You're feedback has been really helpful. Can you share an example of how you're using `AuthState `and `onAuthUIStateChange` in your app? 🙏

**Comment by artidata** [comment]
My use case is almost a copy paste of the [docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#recommended-usage)

```js
import React from 'react';
import './App.css';
import Amplify from 'aws-amplify';
import { AmplifyAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

const AuthStateApp = () => {
    const [authState, setAuthState] = React.useState();
    const [user, setUser] = React.useState();

    React.useEffect(() => {
        return onAuthUIStateChange((nextAuthState, authData) => {
            setAuthState(nextAuthState);
            setUser(authData)
        });
    }, []);

  return authState === AuthState.SignedIn && user ? (
      <div className="App">
          <div>Hello, {user.username}</div>
          <AmplifySignOut />
      </div>
    ) : (
      <AmplifyAuthenticator />
  );
}

export default AuthStateApp;
```
Instead of the rest of the app to be the `children` of `<Authenticator>`, I store the latest  `AuthState` value in the `authState` state and only render the rest of the app when ` authState === AuthState.SignedIn` (conditional rendering).

**Comment by ericclemmons** [comment]
`withAuthenticator` is basically a wrapper for the render-prop use-case here:

```js
export default function SimpleApp() {
  return (
    <Authenticator>
      {({ signOut, user }) => (
		<div className="App">
          <div>Hello, {user.username}</div>
          <button onClick={signOut}>Sign out</button>
        </div>
	  )}
    </Authenticator>
  );
}
```

No need to manage state separately – it's all passed directly to the inner function.

In fact, this is how it's being used internally:

https://github.com/aws-amplify/amplify-ui/blob/5ba49511456daaf2991923f58123f69a66809bd7/packages/react/src/components/Authenticator/Router/index.tsx#L25-L43

**One important thing to note between the previous `@aws-amplify/ui-react` version & this one** – the previous release would render whatever was inside `<AmplifyAuthenticator>` all the time. So you couldn't access `user.username` because it could be `undefined`.

This release fixes that design so that `children` only render when signed in – you can safely access `user` without worrying about errors.

We'll update the docs to mention `withAuthenticator`, but primarily document `<Authenticator>`...
