### ISSUE TITLE
Authenticator: Username cannot be empty error message when refreshing screen after signup

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-ui#818]
Steps to reproduce error below:

1. signup with username/password
2. refresh screen/browser
3. attempt to login and redirect to Confirm Sign Up input
4. input correct auth code into input
5. hit enter

<img width="511" alt="Screen Shot 2021-11-20 at 7 27 08 PM" src="https://user-images.githubusercontent.com/350275/142744766-2fb5f1e1-ae7d-49fc-b833-6e5d629695b7.png">

I am not sure of any workarounds so wanted to report this corner case scenario.

**Comment by wlee221** [comment]
Thanks for opening this issue! 

My initial guess is that 

https://github.com/aws-amplify/amplify-ui/blob/c3a5e175a9a20124659a94293dd770e6790859ac/packages/ui/src/machines/authenticator/actions.ts#L68-L72

this logic is insufficient when you're going `signIn` to `confirmSignUp` because input `name` attribute is different on `signIn`. Will investigate further Monday and give you an update.

**Comment by wlee221** [comment]
Hi @oste, this should be fixed in the latest release. Please let us know if it doesn't work!
