### ISSUE TITLE
'required=false' on amplifyTextField not being respected

### ISSUE THREAD

**Issue by jeff-wishnie** [aws-amplify/amplify-ui#834]
Env:
- Vue3
- @aws-amplify/ui-vue v2.0.0

When adding additional SignIn fields, `required="false"` is not respected, SignIn form still requires these fields.

Code fragment:
```
 <authenticator
      initial-state="signIn"
      :login-mechanisms="['email']"
      :sign-up-attributes="['email']"
    >
      <template v-slot:sign-up-fields>
        <amplify-text-field
          id="name"
          label="Full Name"
          name="name"
          placeholder="Full Name"
          required="true"
        />
        <amplify-text-field
          id="title"
          label="Title"
          name="custom:title"
          placeholder="Professional Title"
          required="false"
        />
        <amplify-text-field
          id="credentials"
          label="Credentials"
          name="custom:credentials"
          placeholder="Professional Credentials"
          required="false"
        />
        <authenticator-sign-up-form-fields />
      </template>
</authenticator>
```

Outcome:
![image](https://user-images.githubusercontent.com/84994260/142930893-47889292-e8f5-4d6a-b192-939f06ef7dfd.png)

Expected Outcome:
Non-required fields should not be required in the UI

**Comment by ericclemmons** [comment]
Yes, this is definitely a bug. I'm not sure how though:
https://github.com/aws-amplify/amplify-ui/blob/f81aa5917f08a1ec112d8f889a6c72d2b1acf614/packages/vue/src/components/primitives/amplify-text-field.vue

So, what we can do is update https://github.com/aws-amplify/amplify-ui/blob/main/examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue to include an input that's _optional_ so that we can ensure this behavior is consistent across all platforms (as well as a test):
> https://github.com/aws-amplify/amplify-ui/blob/main/examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue

**Comment by jeff-wishnie** [comment]
amplify-text-field just passes 'required' onto https://github.com/aws-amplify/amplify-ui/blob/f81aa5917f08a1ec112d8f889a6c72d2b1acf614/packages/vue/src/components/primitives/base-input.vue, which doesn't seem to do anything with it... doesn't pass it on to `<input>`--is that an issue or is there an independent validation mechanism I'm not seeing?

**Comment by ErikCH** [comment]
Hi @jeff-wishnie !

When you're passing the `required` attribute into ` <amplify-text-field>` you're passing it as text instead of a `boolean`. So the text always resolves to true. What you need to do is bind `true` like this `:required="true"` . Could you try that and see if it fixes your problem?

The `base-input` component props I'm passing aren't explicitly set. That's something I could probably improve in the future. Since they aren't declared as `props` they are automatically added to the outermost element in the `base-input` component. Which is `<input>`

**Comment by wlee221** [comment]
Hello @jeff-wishnie, we'll close this as per @ErikCH's comment. Please let us know if problem persists or you have additional questions.

**Comment by jeff-wishnie** [comment]
Arrghh! Yes, that's it--Vue vs. HTML props still gets me from time to time!
