### ISSUE TITLE
Update the Provider for useAuthenticator on the docs

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-ui#918]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

The 'Getting Started' documentation on the new Amplify UI site ([https://ui.docs.amplify.aws/getting-started/installation?platform=react](https://ui.docs.amplify.aws/getting-started/installation?platform=react)) states that you need to add the Provider as:
`import { AmplifyProvider } from '@aws-amplify/ui-react';
`
But after some debugging I think the correct PRovider that needs to be added is:
```
import { Authenticator } from "@aws-amplify/ui-react";

<Authenticator.Provider>
        <App />
      </Authenticator.Provider>
```

### What's the expected behaviour?

To see the right provider needed on the docs

### Help us reproduce the bug!

Just visit the docs site :)

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by Milan-Shah** [comment]
Thank you @jerocosio for opening the issue. @reesscot or @ericclemmons can you please confirm on our end?

**Comment by reesscot** [comment]
Hi @jerocosio,

The `AmplifyProvider` component provides internal logic (id generation needed for field accessibility) as well as the default styling theme used by the Authenticator (see [Theming](https://ui.docs.amplify.aws/theming)). 

For most Authenticator use cases It's not necessary to use `Authenticator.Provider`, as the `Authenticator` component automatically includes it. See [Authenticator.tsx](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/Authenticator.tsx#L22-L31).

Here's a code sample of how you can use both `AmplifyProvider` and `Authenticator` together (though typically you would put AmplifyProvider in your index.ts file wrapping your `App` rather than inside your `App`):

```tsx
import { Amplify } from 'aws-amplify';

import { AmplifyProvider, Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default function App() {
  return (
    <AmplifyProvider>
      <Authenticator>
        {({ signOut, user }) => (
          <main>
            <h1>Hello {user.username}</h1>
            <button onClick={signOut}>Sign out</button>
          </main>
        )}
      </Authenticator>
    </AmplifyProvider>
  );
}
```

Hope that clarifies things. Please let us know if you have any more questions on this.

**Comment by reesscot** [comment]
@jerocosio One further thought I had was that maybe you are trying to use the `useAuthenticator` hook instead of the `Authenticator` component. If so, is there a particular use case you're trying to achieve by using the hook instead of the component that we could help document better?

**Comment by jerocosio** [comment]
Hi @reesscot, yes I'm actually using `useAuthenticator` hook alongside the `Authenticator` component. And if I added `AmplifyProvider` then the hook didn't worked.

But also on the getting started doc, there are some reference to useAuthenticator, that won't work if you follow step by step as you're not adding the right provider :).

This can be seen here for example: [https://ui.docs.amplify.aws/components/authenticator?platform=react#customization](https://ui.docs.amplify.aws/components/authenticator?platform=react#customization) where `const { toResetPassword } = useAuthenticator();` is being referenced.

On my actual implementation I'm only using `signOut` at the moment, as `user`  didn't worked for me and I had to create my own hook.

**Comment by ericclemmons** [comment]
@jerocosio Can you share more about this?
> that won't work if you follow step by step as you're not adding the right provider :)

(What does "won't work" mean? Not render? Throw an error? Render but not _do_ anything?)

The linked documentation is coming from this Next.js example:
> https://github.com/aws-amplify/amplify-ui/blob/main/examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx

https://github.com/aws-amplify/amplify-ui/blob/f1c2d82db913be13425e8b4476983d7cf6f55c40/examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx#L111-L113

All of the components under the `Authenticator` should have access to the `Authenticator.Provider`'s context (otherwise it would throw).

Can you share a full snippet of your implementation so I can help debug the issue? 🙏

**Comment by ericclemmons** [comment]
Closing since we'll be documenting `useAuthenticator` usage separately, but `Authenticator.Provider` is not required for the Authenticator unless you're replacing the entire `<Authenticator>` component.

**Comment by wlee221** [comment]
Hi @jerocosio, as @ericclemmons mentioned `Authenticator.Provider` is not needed unless you want to use it at `<App />` level. 

We're interested in supporting `useAuthenticator` at a more global level, but we would like to understand its use case before we document and support it. Can you please let us know with the use case either on this thread or on a new issue, and we'll be glad to take a look!
