### ISSUE TITLE
Shim Node.JS variables global, process and export! 

### ISSUE THREAD

**Issue by Milan-Shah** [aws-amplify/amplify-ui#930]

**Comment by reesscot** [comment]
I did some research on this issue and found that it's preferred to shim the Node.js globals at the bundler level, rather than at the library level. This allows customers to control how the Node.js globals are shimmed. Here is a summary of polyfilling these globals for the most common build systems:

## Bundlers

### Create React App
Create React App already shims the Node globals, so no changes are needed.

### Parcel
Parcel already shims the Node globals, so no changes are needed.

### Vite JS
Vite can be shimmed as detailed in our [Getting Started](https://ui.docs.amplify.aws/getting-started/installation#vite) guide.

However, the key is to shim the globals in the `index.html` file like so:
```
  <script>
    window.global = window;
    window.process = {
      env: { DEBUG: undefined },
    };
    var exports = {};
  </script>
</body>
```



### Webpack5
In version 5 of Webpack the Node globals shims where removed. We can add them back using [node-polyfill-webpack-plugin](https://www.npmjs.com/package/node-polyfill-webpack-plugin)

*1. Add Node polyfill plugin*
```bash
npm install node-polyfill-webpack-plugin -D
```

*2. Add the plugin to your `webpack.config.js` plugins:*
```js
  plugins: [
    new NodePolyfillPlugin(), // Polyfill Node.js globals (e.g. global, process, etc)
  ],
```

Check out the https://github.com/reesscot/amplify-ui-build-systems repo for working examples with each build system.
